/*****************************************************************************
Author: Cesar Roncancio
Date:   08/06/2021

Description:
In this assignment, you will create the game called Rock Paper Scissors game with a little twist to it. In this version, you will also include Lizard and Spock. This means the players have the choice of Rock, Paper, Scissors, Lizard, and Spock.

The program will play the game between a user and the computer. The game will continue until there is a winner to the game, the user should not be prompted to see if they want to continue when there is a tie in the game. If the game is a tie then the program must make the user play again, until there is a winner. Once there is a winner, the program (game) must end.

The computers choice will be a random number generated by the program using the random number generator. The number must be limited to the following values:

Rock
Paper
Scissors
Lizard
Spock
Use a menu to prompt the user for their choice, using the same values as above. The program will then display the computer’s choice and the user’s choice in a textual format. Meaning if the computer random number is 3 then it should display something like “The computer choice is Scissors”.

The program will then determine if there is a winner or a tie. If there is a winner the program must tell the user, the rule the winner won by (listed below).

A winner is determined using the following rules:

Scissors cut paper
Paper covers rock
Rock crushes lizard
Lizard poisons Spock
Spock smashes (or melts) scissors
Scissors decapitate lizard
Lizard eats paper
Paper disproves Spock
Spock vaporizes rock
Rock breaks scissors
The program must be divided into functions with at least the following functions:

int getUserChoice()
Displays a menu of choices
Prompts the user for their choice from the menu
Return the users choice as an integer to main
int getComputerChoice()
Use the random number generator to create the computer's choice
returns the computer's choice as an integer to main
bool determineWinner(int userChoice, int compChoice)
Uses the two parameters to determine if there is a winner based on the rules provided above.
Return true if there is a winner, false otherwise (used to determine if tie so that the game can continue in main).
If a winner, then the correct message must be display indicating who won and by what rule.
void displayChoice(int choice)
To be used display user choice.
To be used to display computer choice.
Should be called two times o Display the choice as text not numeric (Such as “Rock” for choice of 1).
The program must indicate whose choice it is. Does not need to be done in the function
Function just displays the choice, a single word.

Pseudo code:
   Start
	-Declare variables and Functions
	-Call getUserChoice function and assign value to userGuess
	-Call getComputerChoice function and addign value to compGuess
	-Call displayChoice receiving compGuess
	-Call determineWinner receiving userGuess and compGuess
	-Function getUserChoice
	-Display "1 - Rock"
	-Display "2 - Paper"
	-Display "3 - Scissors"
	-Display "4 - Lizard"
	-Display "5 - Spock"
	-Display "Enter your guess: "
	-Input choice
	-While choice is not between 1 and 5
	-Display "choice must be between 1 and 5!"
	-Display "Enter a valid guess: "
	-Input choice
	-Return choice
	-Function getComputerChoice
	-choice = (random number modulo 5) + 1
	-Return choice
	-Function determineWinner receives user and comp
	-While user equals comp 
	-winner equals false
	-Call getUserChoice and assign to user
	-Call getComputerChoice and assign to comp
	-Call displayChoice receiving comp
	-If user is different from comp
	-winner equals true
	-If user got scissors and comp got paper
	-Display "Scissors cut paper. You Win!"
	-If user got paper and comp got rock
	-Display "Paper covers rock. You Win!"
	-If user got rock and comp got lizard
	-Display "Rock crushes lizard. You Win!"
	-If user user got lizard and comp got spock
	-Display "Lizard poisons Spock. You Win!"
	-If user got spock and comp got scissors
	-Display "Spock melts scissors. You Win!"
	-If user got scissors and comp got lizard
	-Display "Scissors decapitate lizard. You Win!"
	-If user got lizard and comp got paper
	-Display "Lizard eats paper. You Win!"
	-If user got paper and comp got spock
	-Display "Paper disproves Spock. You Win!"
	-If user got spock and comp got rock
	-Display "Spock vaporizes rock. You Win!"
	-If user got rock and comp got scissors
	-Display "Rock breaks scissors. You Win!"
	-If comp got scissors and user got paper
	-Display "Scissors cut paper. You Lose!"
	-If comp got paper and user got rock
	-Display "Paper covers rock. You Lose!"
	-If comp got rock and user got lizard
	-Display "Rock crushes lizard. You Lose!"
	-If comp user got lizard and user got spock
	-Display "Lizard poisons Spock. You Lose!"
	-If comp got spock and user got scissors
	-Display "Spock melts scissors. You Lose!"
	-If comp got scissors and user got lizard
	-Display "Scissors decapitate lizard. You Lose!"
	-If comp got lizard and user got paper
	-Display "Lizard eats paper. You Lose!"
	-If comp got paper and user got spock
	-Display "Paper disproves Spock. You Lose!"
	-If comp got spock and user got rock
	-Display "Spock vaporizes rock. You Lose!"
	-If comp got rock and user got scissors
	-Display "Rock breaks scissors. You Lose!"
	-Return winner
	-Function displayChoice receives compChoice
	-Display "Computer guess: "
	-Display compChoice
	-If compChoice equals 1
	-Display "The computer choice is Rock "
	-If compChoice equals 2
	-Display "The computer choice is Paper "
	-If compChoice equals 3
	-Display "The computer choice is Scissors "
	-If compChoice equals 4
	-Display "The computer choice is Lizard "
	-If compChoice equals 5
	-Display "The computer choice is Spock "
   End
*******************************************************************************/


#include <iostream>
#include <ctime>
using namespace std;

int getUserChoice();
int getComputerChoice();
bool determineWinner(int, int);
void displayChoice(int);

const int ROCK = 1,
PAPER = 2,
SCISSORS = 3,
LIZARD = 4,
SPOCK = 5;

int main() {
	int userGuess,
		compGuess;

	userGuess = getUserChoice();
	compGuess = getComputerChoice();
	displayChoice(compGuess);
	determineWinner(userGuess, compGuess);

	system("pause");
	return 0;
}

int getUserChoice() {
	int choice;
	cout << "1 - Rock" << endl
		<< "2 - Paper" << endl
		<< "3 - Scissors" << endl
		<< "4 - Lizard" << endl
		<< "5 - Spock" << endl << endl
		<< "Enter your guess: ";
	cin >> choice;
	while ((choice < 1) || (choice > 5)) {
		cout << "choice must be between 1 and 5!" << endl << endl
			<< "Enter a valid guess: ";
		cin >> choice;
	}
	return choice;
}

int getComputerChoice() {
	unsigned seed = time(0);
	srand(seed);
	int choice = (rand() % (5)) + 1;
	return choice;
}

bool determineWinner(int user, int comp) {
	bool winner;
	while (user == comp) {
		winner = false;
		user = getUserChoice();
		comp = getComputerChoice();
		displayChoice(comp);
	}
	if (user != comp) {
		winner = true;
		// winning scenarios
		if ((user == SCISSORS) && (comp == PAPER)) {
			cout << "Scissors cut paper. You Win!" << endl << endl;
		}
		if ((user == PAPER) && (comp == ROCK)) {
			cout << "Paper covers rock. You Win!" << endl << endl;
		}
		if ((user == ROCK) && (comp == LIZARD)) {
			cout << "Rock crushes lizard. You Win!" << endl << endl;
		}
		if ((user == LIZARD) && (comp == SPOCK)) {
			cout << "Lizard poisons Spock. You Win!" << endl << endl;
		}
		if ((user == SPOCK) && (comp == SCISSORS)) {
			cout << "Spock melts scissors. You Win!" << endl << endl;
		}
		if ((user == SCISSORS) && (comp == LIZARD)) {
			cout << "Scissors decapitated lizard. You Win!" << endl << endl;
		}
		if ((user == LIZARD) && (comp == PAPER)) {
			cout << "Lizard eats paper. You Win!" << endl << endl;
		}
		if ((user == PAPER) && (comp == SPOCK)) {
			cout << "Paper disproves Spock. You Win!" << endl << endl;
		}
		if ((user == SPOCK) && (comp == ROCK)) {
			cout << "Spock vaporizes rock. You Win!" << endl << endl;
		}
		if ((user == ROCK) && (comp == SCISSORS)) {
			cout << "Rock breaks scissors. You Win!" << endl << endl;
		}

		// losing senarios
		if ((comp == SCISSORS) && (user == PAPER)) {
			cout << "Scissors cut paper. You Lose!" << endl << endl;
		}
		if ((comp == PAPER) && (user == ROCK)) {
			cout << "Paper covers rock. You Lose!" << endl << endl;
		}
		if ((comp == ROCK) && (user == LIZARD)) {
			cout << "Rock crushes lizard. You Lose!" << endl << endl;
		}
		if ((comp == LIZARD) && (user == SPOCK)) {
			cout << "Lizard poisons Spock. You Lose!" << endl << endl;
		}
		if ((comp == SPOCK) && (user == SCISSORS)) {
			cout << "Spock smashes scissors. You Lose!" << endl << endl;
		}
		if ((comp == SCISSORS) && (user == LIZARD)) {
			cout << "Scissors decapitated lizard. You Lose!" << endl << endl;
		}
		if ((comp == LIZARD) && (user == PAPER)) {
			cout << "Lizard eats paper. You Lose!" << endl << endl;
		}
		if ((comp == PAPER) && (user == SPOCK)) {
			cout << "Paper disproves Spock. You Lose!" << endl << endl;
		}
		if ((comp == SPOCK) && (user == ROCK)) {
			cout << "Spock vaporizes rock. You Lose!" << endl << endl;
		}
		if ((comp == ROCK) && (user == SCISSORS)) {
			cout << "Rock breaks scissors. You Lose!" << endl << endl;
		}
	}

	return winner;
}

void displayChoice(int compChoice) {

	cout << "Computer guess: " << compChoice << endl << endl;
	if (compChoice == 1) {
		cout << "The computer choice is Rock " << endl << endl;
	}
	else if (compChoice == 2) {
		cout << "The computer choice is Paper " << endl << endl;
	}
	else if (compChoice == 3) {
		cout << "The computer choice is Scissors " << endl << endl;
	}
	else if (compChoice == 4) {
		cout << "The computer choice is Lizard " << endl << endl;
	}
	else if (compChoice == 5) {
		cout << "The computer choice is Spock " << endl << endl;
	}

}